### ISSUE TITLE
Explain me like I'm 5 what this extension does

### ISSUE THREAD

**Issue by illia-karpenkov** [microsoft/vscode-test-adapter-converter#32]
Honesty I'm puzzled why this extension exists in the first place, even after reading description several times. 
Phrase 'converts from the Test Explorer UI API into native VS Code testing' assumes some prior knowledge which people may not have when trying to answer the question why this thing is in their vscode plugins list. It would be cool if someone could give more information about how things evolved into the way they are right now, what 'Test Explorer UI API' is, where is it used, how is it different from 'native VS Code testing' api, etc.
Considering the fact that its been downloaded more than million times, it deserves a better documentation, especially for beginners. 
Being a software engineer with over 17 years of experience (mostly in a dotnet stack) I still have no clue what this thing does after reading its github readme page. Pretty sure it does something very useful and thanks a bunch for your hard work!

**Comment by connor4312** [comment]
Prior to last year, showing tests in VS Code was mostly accomplished by using an extension created by our community, the [Test Explorer UI](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer). This extension exposed its own API for extensions to use, as well as an API for other extensions to introspect those extensions.

Last year, I added a native [testing API](https://code.visualstudio.com/api/extension-guides/testing) to VS Code which removes the need for that extension--and as mentioned in its readme, generally authors should build against that API rather than depending on the Test Explorer UI. However, there are lots of old extensions which may never update to the new API. This extension uses the introspection API available on the Test Explorer UI to expose those extensions via the native testing API.
