### ISSUE TITLE
What does this extension do?

### ISSUE THREAD

**Issue by steven-rothwell** [microsoft/vscode-test-adapter-converter#35]
The readme states:

"This is an extension that converts from the [Test Explorer UI](https://marketplace.visualstudio.com/items?itemName=hbenl.vscode-test-explorer) API into native VS Code testing. You can use this by setting testExplorer.useNativeTesting: true in your user settings."

Why would I want to utilizing native VS Code testing?  What is native VS Code testing?  I don't know why this extension was auto-installed.

**Comment by connor4312** [comment]
The Test Explorer UI provides its own UI for unit tests using a custom tree view. Last year we released a new [testing API](https://code.visualstudio.com/api/extension-guides/testing) which has more features and deeper integration into VS Code. This extension translates extensions built for the Test Explorer UI extension into the native testing API. This extension was auto installed since it's a dependency of the Test Explorer UI extension.
